# Generated by Django 4.2.2 on 2023-08-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('LB', 'lb'), ('OZ', 'oz'), ('FL OZ', 'fl oz'), ('ITEM', 'item')], default='oz', max_length=6),
        ),
    ]
