# Generated by Django 4.2.2 on 2023-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('lb', 'lb'), ('oz', 'oz'), ('fl oz', 'fl oz'), ('item', 'item')], default='oz', max_length=6),
        ),
    ]
