# Generated by Django 4.2.2 on 2023-08-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ingredient_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='quantity_avail',
            new_name='quantity_available',
        ),
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='quantity_req',
            new_name='quantity_required',
        ),
    ]
