# Generated by Django 4.2.2 on 2023-08-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_quantity_avail_ingredient_quantity_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
