# Generated by Django 4.2.2 on 2023-08-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_menuitem_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_requirements', to='inventory.menuitem'),
        ),
    ]
