# Generated by Django 4.2.2 on 2023-08-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_reciperequirement_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
