# Generated by Django 5.0.2 on 2024-05-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Доступное количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('кг', 'кг'), ('л', 'л'), ('шт.', 'шт.')], default='oz', max_length=6, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена за единицу, руб.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity_required',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Требуемое количество'),
        ),
    ]
